### ISSUE TITLE
AppCivist Patterns Initialization

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patternlab-php#3]
Bootstrap AppCivist Beta front-end patterns with initial html partials for the components in the new wireframes, which are available in the [AppCivist UX Running Notes](https://docs.google.com/document/d/1s9XovWP7CFtt8NM4FywNX2-Rb_1eH3YxS-76mvzdu_Y/edit#bookmark=id.tlxxrafqoqr)

**Comment by pablodefendini** [comment]
closed in favor of [the same epic](https://github.com/socialappslab/appcivist-patterns/issues/2) on the new repo
